api/urls.py
from django.urls import path
from . import views_author, views_book, views_order, views_user


urlpatterns = [
    path('author/', views_author.ApiAuthors.as_view()),
    path('author/<int:pk>/', views_author.ApiAuthorPK.as_view()),
    path('book/', views_book.ApiBooks.as_view()),
    path('book/<int:pk>/', views_book.ApiBookPK.as_view()),
    path('order/', views_order.ApiOrders.as_view()),
    path('order/<int:pk>/', views_order.ApiOrderPK.as_view()),
    path('user/', views_user.ApiCustomUser.as_view()),
    path('user/<int:user_pk>/order/<int:order_pk>/', views_user.ApiUserOrderPK.as_view()),
    path('user/<int:pk>/', views_user.ApiCustomUserPK.as_view()),
]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('order/', include('order.urls'), name='order'),
    path('book/', include('book.urls'), name='books'),
    path('author/', include('author.urls'), name='author'),
    path('users/', include('authentication.urls'), name='users'),
    path('api/v1/', include('api.urls'), name='api'),
    path('admin/', admin.site.urls),
]

order/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.order_list, name='order_list'),
    path('add/', views.add_order, name='add_order'),
    path('edit/<int:pk>', views.edit_order, name='edit_order'),
    path('user_id/<int:pk>', views.order_by_user_id, name='order_user_id'),
    path('not_returned/', views.not_returned_books, name='not_returned_books'),
]

order/models.py
from datetime import datetime
from django.db import models, DataError, IntegrityError

from authentication.models import CustomUser
from book.models import Book
import datetime


class Order(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    end_at = models.DateTimeField(null=True, blank=True)
    plated_end_at = models.DateTimeField()

    def __str__(self):
        """
        Magic method is redefined to show all information about Book.
        :return: book id, book name, book description, book count, book authors
        """
        return str(self.to_dict())[1:-1]

    def __repr__(self):
        """
        This magic method is redefined to show class and id of Book object.
        :return: class, id
        """
        return f'{self.__class__.__name__}(id={self.id})'

    def to_dict(self):
        return {
            'id': self.id,
            'user': self.user,
            'book': self.book,
            'created_at': str(self.created_at),
            'end_at': str(self.end_at) if self.end_at else self.end_at,
            'plated_end_at': str(self.plated_end_at)
        }

    @staticmethod
    def create(user, book, plated_end_at):

        order = Order(user=user, book=book, plated_end_at=plated_end_at)
        if book.count <= len([order for order in Order.get_not_returned_books() if order.book.id == book.id]):
            return
        try:
            order.save()
            return order
        except (IntegrityError, AttributeError, DataError, ValueError) as err:
            # print(err)
            # LOGGER.error("Wrong attributes or relational integrity error")
            pass

    @staticmethod
    def get_by_id(order_id):

        try:
            user = Order.objects.get(id=order_id)
            return user
        except Order.DoesNotExist:
            pass

    def update(self, plated_end_at=None, end_at=None):
        if plated_end_at:
            self.plated_end_at = plated_end_at
        if end_at:
            self.end_at = end_at
        self.save()

    @staticmethod
    def get_all():
        all_order = list(Order.objects.all())
        return all_order

    @staticmethod
    def get_not_returned_books():
        orders = [order for order in Order.get_all() if order.end_at is None]
        return orders

    @staticmethod
    def not_returned_on_time():
        orders = [order for order in Order.get_all() if
                  (order.end_at and order.end_at > order.plated_end_at) or
                  (not order.end_at and
                   order.plated_end_at < datetime.datetime.now(order.plated_end_at.tzinfo))]
        return orders

    @staticmethod
    def delete_by_id(order_id):
        """
        :param user_id: an id of a user to be deleted
        :type user_id: int
        :return: True if object existed in the db and was removed or False if it didn't exist
        """

        try:
            user = Order.objects.get(id=order_id)
            user.delete()
            return True
        except Order.DoesNotExist:
            # LOGGER.error("User does not exist")
            pass
        return False

order/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ("user", "book", "end_at", "plated_end_at")
        labels = {"user": "user",
                  "book": "book",
                  "end_at": "Return date (%Y-%m-d %H:%M:S)",
                  "plated_end_at": "Planned return (%Y-%m-d %H:%M:S)"
                  }

order/views.py
from django.shortcuts import render

from authentication.models import CustomUser
from order.models import Order
from .forms import OrderForm


def order_list(request):
    sorting = request.GET.get('sorting')
    param = request.GET.get('param')

    if sorting == "desc":
        order_list = Order.objects.all().order_by(param).reverse()
    else:
        order_list = Order.objects.all().order_by(param)

    title = f"Orders by sorting:{param}({sorting})"
    context = {'order_list': order_list,
               'sorting': sorting,
               'param': param,
               "title": title,
               }
    return render(request, 'order/order_list.html', context)


def not_returned_books(request):
    user_info = Order.not_returned_on_time
    title = "doesn't hand over books on time"
    context = {'not_returned_books': user_info,
               "title": title,
               }
    return render(request, 'order/not_returned_books.html', context)


def order_by_user_id(request, pk):
    order_list = Order.objects.all().filter(user__pk=pk)
    user_name = CustomUser.get_by_id(pk)
    title = f"Order by user ID:{pk}"
    context = {"user_id": pk,
               "order_list": order_list,
               "user_name": user_name,
               "title": title,
               }
    return render(request, 'order/user_id.html', context)


def add_order(request):
    context = {"title": "add order"
               }
    if request.method == "POST":
        form_order = OrderForm(request.POST)
        if form_order.is_valid():
            if form_order.has_changed():
                form_order.save()
                context["create"] = "order was created"
            else:
                context["form_not_changed"] = "order wasn't created"
    else:
        context["form"] = OrderForm()
    return render(request, 'order/add_order.html', context)


def edit_order(request, pk):
    order = Order.get_by_id(pk)
    context = {"order": order,
               "title": f"id:{pk}"
               }
    if request.method == "POST":
        if "delete" in request.POST:
            order.delete()
            context["delete"] = "User was deleted"
        if "save" in request.POST:
            form_order = OrderForm(request.POST, instance=order)
            if form_order.is_valid():
                if form_order.has_changed():
                    form_order.save()
                    context["saved"] = "changes was saved"
                else:
                    context["form_not_changed"] = "form not changed"
    else:
        context["form"] = OrderForm(instance=order)
    return render(request, 'order/edit_order.html', context)

templates/order/add_order.html
{% extends 'index.html' %}
{% block content %}

<h2>{{ title }}</h2>

{% if create %}
    {{ create }}
{% elif form_not_changed %}
    {{ form_not_changed }}
{% elif not form_not_changed %}
    <form action="{% url 'add_order' %}" method="POST">
        {% csrf_token %}
        <style>select {width:400px;}</style>
            <p><label for="id_user">user:</label>{{ form.user }}</p>
            <p><label for="id_book">book:</label>{{ form.book }}</p>
            <p><label for="id_plated_end_at">Planned return (%Y-%m-d %H:%M:S):</label>{{ form.plated_end_at }}</p>
        <button type="Submit" name="save">Save</button>
    </form>

{% endif %}
{% endblock %}

templates/order/edit_order.html
{% extends 'index.html' %}
{% block content %}

<h2>Order id: {{ order.pk }}</h2>

{% if delete %}
    {{ delete }}
{% elif saved %}
    {{ saved }}
{% elif form_not_changed %}
    {{ form_not_changed }}
{% elif not form_not_changed %}
    <form action="{% url 'edit_order' order.pk %}" method="POST">
        {% csrf_token %}
            {{ form.as_p }}
        <button type="Submit" name="save">Save</button>
        <button type="Submit" name="delete">Delete</button>
    </form>
{% endif %}
{% endblock %}

templates/order/not_returned_books.html
{% extends 'index.html' %}
{% block content %}
<h2>show information about users who does not hand over books on time</h2>

<table>
    <tr>
        <th>order ID</th>
        <th>user ID</th>
        <th>User</th>
        <th>Book name</th>
        <th>Authors</th>
        <th>Actual return date</th>
        <th>Return date until</th>
    </tr>
    {% for order in not_returned_books %}
        <tr>
            <td>{{  order.id }}</td>
            <td>{{  order.user.id }}</td>
            <td>{{  order.user.first_name }}
                {{  order.user.middle_name }}
                {{  order.user.last_name }}</td>
            <td>{{  order.book.name }}</td>
            <td>{% for author in order.book.authors.all %}
                    {{ author.name }} {{ author.surname }}
                {% endfor %}
            </td>
            <td>{{  order.end_at }}</td>
            <td>{{  order.plated_end_at }}</td>
        </tr>
    {% endfor %}

</table>

{% endblock %}

templates/order/order_list.html
{% extends 'index.html' %}
{% block content %}

<h2>show information about all orders sorted by date ({{ param }},  {{ sorting }})</h2>

<a href="{% url 'add_order' %}">+ Add order</a>
<table>
    <tr>
        <th>ID</th>
        <th>Book ID</th>
        <th>Book name</th>
        <th>Authors</th>
        <th>User ID</th>
        <th>User</th>
        <th>Created at</th>
        <th>Actual return date</th>
        <th>Return date until</th>
        <th></th>
    </tr>
    {% for order in order_list %}
    <tr>
        <td>{{order.id}}</td>
        <td>{{order.book.pk}}</td>
        <td>{{order.book.name}}</td>
        <td>{% for author in order.book.authors.all %}
                {{ author.surname }}
                {{ author.name }}
                {{ author.patronymic }}
            {% endfor %}
        </td>
        <td>{{ order.user.id }}</td>
        <td>
            {{ order.user.last_name}}
            {{ order.user.first_name}}
            {{ order.user.middle_name}}
        </td>
        <td>{{order.created_at}}</td>
        <td>{{order.end_at}}</td>
        <td>{{order.plated_end_at}}</td>
        <td><a href="{% url 'edit_order' order.id %}">edit</a></td>
    </tr>
    {% endfor %}

{% endblock %}

</table>

templates/order/user_id.html
{% extends 'index.html' %}
{% block content %}

<h2>show all books given by specific user by id: {{ user_id }}</h2>

<table>
    <caption>{{ user_name.last_name }}
             {{ user_name.first_name }}
             {{ user_name.middle_name }}
    </caption>
    <tr>
        <th>Order ID</th>
        <th>Book ID</th>
        <th>Book name</th>
        <th>Authors</th>
        <th>Order created</th>
        <th>Actual return date</th>
        <th>Return date until</th>
    </tr>
    {% for order in order_list %}
    <tr>
        <td>{{order.id}}</td>
        <td>{{order.book.id}}</td>
        <td>{{order.book.name}}</td>
        <td>{% for author in order.book.authors.all %}
            {{author.surname}} {{author.name}} {{author.patronymic}}
            {% endfor %}
        </td>
        <td>{{order.created_at}}</td>
        <td>{{order.end_at}}</td>
        <td>{{order.plated_end_at}}</td>
    </tr>
    {% endfor %}

{% endblock %}

</table>